pesquisa_alter/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from pesquisa_alter.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('person/json/', v.person_json, name='person_json'),
    path('person/<int:pk>/', v.person_detail, name='person_detail'),
    path('person/pesquisa/add/', v.pesquisa_add, name='pesquisa_add'),
    path(
        'pesquisa/',
        TemplateView.as_view(template_name='add_pesquisa.html'),
        name='add_pesquisa'
    ),
]

pesquisa_alter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pesquisa_alter.core.urls')),
    path('admin/', admin.site.urls),
]

pesquisa_alter/core/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Person(models.Model):
    cdalterdata = models.IntegerField('Cód. Alterdata')
    name = models.CharField('nome', max_length=100)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField('telefone', max_length=11, null=True, blank=True)
    # GENDER = (
    #     ('0', ''),
    #     ('man', 'homem'),
    #     ('woman', 'mulher'),
    # )
    # gender = models.CharField(
    #     'sexo',
    #     max_length=5,
    #     choices=GENDER,
    #     default='0'
    # )

    class Meta:
        ordering = ('name',)
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return self.name

    def to_dict_json(self):
        return {
            'cdalterdata': self.cdalterdata,
            'name': self.name,
            'email': self.email,
            'phone': self.phone,
            # 'gender': self.get_gender_display(),
        }

    def get_absolute_url(self):
        return reverse('pesquisa_alter:add_pesquisa', args=[str(self.id)])


class Questions(models.Model):
    LEVEL_CHOICES = (
        ('0', 'Indefinido'),
        ('1', 'Dependencia'),
        ('2', 'Confianca'),
        ('3', 'Comprometimento'),
        ('4', 'Preditiva'),
        ('5', 'Comprometimento'),
    )
    question = models.CharField('Pergunta', max_length=200)
    level = models.CharField('Nível', max_length=15,
                             choices=LEVEL_CHOICES, default='0')

    class Meta:
        verbose_name = 'Questão'
        verbose_name_plural = 'Questões'
        ordering = ('-level',)

    def __str__(self):
        return self.question


class PesquisaManager(models.Manager):

    def add_question(self, search_key, question):
        pesquisa, created = self.get_or_create(
            search_key=search_key, question=question)
        if not created:
            pesquisa.person = pesquisa.person
            pesquisa.question = pesquisa.question
            pesquisa.save()
        return pesquisa


class Pesquisa(models.Model):
    RESPOSTA_CHOICES = (
        ('V', 'Verdadeiro'),
        ('F', 'Falso'),
        ('I', 'Indefinido'),
    )
    search_key = models.CharField(
        'Chave da pesquisa', max_length=200, db_index=False)
    person = models.ForeignKey(
        'core.person', related_name='Pessoa', on_delete=models.CASCADE)
    researched = models.CharField('Entrevistado', max_length=200)
    question = models.ForeignKey(
        'core.Questions', related_name='Pergunta', on_delete=models.CASCADE,)
    response = models.CharField(
        'Resposta', max_length=1, choices=RESPOSTA_CHOICES, default='I')
    # participation_on = models.DateField('período da pesquisa', default=timezone.now)
    participation_on = models.DateField(
        'período da pesquisa',
        auto_now_add=True,
        auto_now=False
    )
    created_on = models.DateTimeField(
        'solicitado em',
        auto_now_add=True,
        auto_now=False
    )

    objects = PesquisaManager()

    class Meta:
        verbose_name = 'Pesquisa'
        verbose_name_plural = 'Pesquisas'
        unique_together = (('search_key', 'person', 'question'),)
        ordering = ('-participation_on',)

    def __str__(self):
        return self.question.question

    # def get_absolute_url(self):
    #     return reverse('scheduling:agendamento')

pesquisa_alter/core/forms.py
from django import forms
from pesquisa_alter.core.models import Pesquisa


class PesquisaForm(forms.ModelForm):
    # person = forms.ModelChoiceField(label='Cliente', widget=forms.Select(
    #     attrs={'class': 'form-control'}), required=True, queryset=Person.objects.all())
    # response = forms.ChoiceField(label='Resposta',  widget=forms.Select(
    # attrs={'class': 'form-control'}), required=True,
    # choices=RESPOSTA_CHOICES)

    class Meta:
        model = Pesquisa
        fields = (
            'search_key',
            'person',
            'researched',
        )

pesquisa_alter/core/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from .models import Person, Questions, Pesquisa
from .forms import PesquisaForm


def index(request):
    context = {}
    person_list = Person.objects.all()
    context['person_list'] = person_list
    return render(request, 'index.html', context)


def person_detail(request, pk):
    context = {}
    person = get_object_or_404(Person, pk=pk)
    context['person'] = person
    # Retornando todas as pesquisas de uma pessoa.
    pesquisas = Pesquisa.objects.filter(person=person)
    context['pesquisas'] = pesquisas
    return render(request, 'person_detail.html', context)


def person_json(request):
    persons = Person.objects.all()
    data = [person.to_dict_json() for person in persons]
    response = {'data': data}
    return JsonResponse(response)


def pesquisa_add(request):
    template_name = 'pesquisa_add.html'
    if request.method == 'POST':
        form = PesquisaForm(request.POST)
        if form.is_valid():
            data = dict(
                search_key=form.cleaned_data['search_key'],
                person=form.cleaned_data['person'],
                researched=form.cleaned_data['researched'],
                questions=Questions.objects.all(),
            )
            criar_pesquisa(**data)
            # Não usar o método save().
            # form.save()
            return redirect('core:index')
    else:
        form = PesquisaForm()
    context = {'form': form}
    return render(request, template_name, context)


def criar_pesquisa(**data):
    # Pegando somente as perguntas
    questions = data['questions']
    pesquisas = []
    for question in questions:
        obj = Pesquisa(
            search_key=data['search_key'],
            person=data['person'],
            researched=data['researched'],
            question=question
        )
        pesquisas.append(obj)
    Pesquisa.objects.bulk_create(pesquisas)

pesquisa_alter/core/templates/add_pesquisa.html
{% extends "base_materialize.html" %}
{% load static %}

{% block content %}

<div class="container">


<div class="container expand-on-small-only">
    <div class="row valign change-form">
        <div class="m8 offset-m2 l8 offset-l2">
            <div class="card" id="card-radius">
            <form method="POST" enctype="multipart/form-data" class="viewform">{% csrf_token %}

                <div class="card-content">
                    <div class="row">
                        <div class="input-field col s12">
                          <input id="Entrevistado" type="text" class="validate">
                          <label for="Entrevistado">Entrevistado</label>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                          <input placeholder="Mês/Ano da pesquisa." type="text" class="datepicker">
                        </div>
                    </div>
                </div>

                <div class="card-action">
                    <div class="right-align">
                        <button class="waves-effect waves-light btn" type="submit">Enviar</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>




</div>

{% endblock content %}

{% block js %}
<script>

  $(document).ready(function(){
    $('.datepicker').datepicker(
        {
            format: 'mm/yyyy',
            i18n: {
                months: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
                monthsShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
                weekdays: ["Domingo","Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
                weekdaysShort: ["Dom","Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
                weekdaysAbbrev: ["D","S", "T", "Q", "Q", "S", "S"]
            }
        }
    );
  });

</script>
{% endblock js %}

pesquisa_alter/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
      <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <!--BASICO CSS-->
        <!--<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">-->

        <!--MATERIAL CSS-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.material.min.css">

        <!--<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">-->
        <!--<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">-->
        <!--<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>-->



    </head>

    <body>
        <main role="main">

        {% block content %}{% endblock content %}

        </main>


        <!--BASICO JS-->
        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <!--<script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>-->

        <!--JS COM MATERIALIZE-->
        <script src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>

      {% block js %}{% endblock js %}
    </body>
</html>

pesquisa_alter/core/templates/base_materialize.html
<!DOCTYPE html>
<html lang="en">
    <head>
      <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <!--BASICO CSS-->
        <!--<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">-->

        <!--MATERIAL CSS-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.material.min.css">

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">





    </head>

    <body>
        <main role="main">

        {% block content %}{% endblock content %}

        </main>


        <!--BASICO JS-->
        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <!--<script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>-->

        <!--JS COM MATERIALIZE-->
        <script src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

      {% block js %}{% endblock js %}
    </body>
</html>

pesquisa_alter/core/templates/base_materialize_bkp.html
<!DOCTYPE html>
<html lang="en">
    <head>
      <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <!--BASICO CSS-->
        <!--<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">-->

        <!--MATERIAL CSS-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.material.min.css">

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">





    </head>

    <body>
        <main role="main">

        {% block content %}{% endblock content %}

        </main>


        <!--BASICO JS-->
        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <!--<script src="https://cdn.datatables.net/1.10.19/js/dataTables.jqueryui.min.js"></script>-->

        <!--JS COM MATERIALIZE-->
        <script src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

      {% block js %}{% endblock js %}
    </body>
</html>

pesquisa_alter/core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <p>Exemplo do uso de DataTables com Django.</p>
    <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p> -->
  </div>
</div>

<div class="container">
   <!--Example row of columns-->
  <!--<div class="row">-->
    <!--<div class="col s6">-->
      <!--<h2>Contatos</h2>-->
      <!--<table id="myTable1" class="mdl-data-table" style="width:100%">-->
        <!--<thead>-->
          <!--<tr>-->
            <!--<th>Nome</th>-->
            <!--<th>E-mail</th>-->
            <!--<th>Telefone</th>-->
          <!--</tr>-->
        <!--</thead>-->
        <!--<tbody>-->
          <!--{% for person in person_list %}-->
            <!--<tr>-->
              <!--<td>{{ person.name }}</td>-->
              <!--<td>{{ person.email }}</td>-->
              <!--<td>{{ person.phone }}</td>-->
              <!--&lt;!&ndash;<td>{{ person.get_gender_display }}</td>&ndash;&gt;-->
            <!--</tr>-->
          <!--{% endfor %}-->
        <!--</tbody>-->
      <!--</table>-->
    <!--</div>-->

    <div class="col s12">
      <h2>Clientes</h2>

        <table id="myTable2" class="table mdl-data-table" style="width:100%">
          <thead>
            <tr>
              <th>Código</th>
              <th>Nome</th>
              <th>E-mail</th>
              <th>Telefone</th>
            </tr>
          </thead>
          <tbody>
            {% for person in person_list %}
              <tr>
                <td>{{ person.cdalterdata }}</td>
                <td>
                  <a href="{% url 'core:person_detail' person.pk %}">{{ person.name }}</a>
                </td>
                <td>{{ person.email }}</td>
                <td>{{ person.phone }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
  </div>


</div> <!-- /container -->

{% endblock content %}

{% block js %}

<script src=" static 'js/data.js' %}"></script>

{% endblock js %}

pesquisa_alter/core/templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Exemplo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=".">Contatos</a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
  </div>
</nav>

pesquisa_alter/core/templates/person_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <h1>Cliente {{ person.name }} <a class="btn" href="{% url 'core:pesquisa_add' %}">Novo</a></h1>
  <h2>Pesquisas</h2>

  <table id="myTable" class="table mdl-data-table" style="width:100%">
    <thead>
      <tr>
        <th>Chave de pesquisa</th>
        <th>Nome</th>
        <th>Pergunta</th>
        <th>Resposta</th>
        <th>Período da pesquisa</th>
      </tr>
    </thead>
    <tbody>
      {% for pesquisa in pesquisas %}
        <tr>
          <td>{{ pesquisa.search_key }}</td>
          <td>{{ pesquisa.person }}</td>
          <td>{{ pesquisa.question }}</td>
          <td>{{ pesquisa.get_response_display }}</td>
          <td>{{ pesquisa.participation_on }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

pesquisa_alter/core/templates/pesquisa_add.html
{% extends "base_materialize.html" %}
{% load static %}

{% block content %}

<div class="container">
  <h1>Nova pesquisa</h1>



<div class="container expand-on-small-only">
    <div class="row valign change-form">
        <div class="m8 offset-m2 l8 offset-l2">
            <div id="card-radius">
              <form action="." method="POST">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <div class="card-action">
                      <div class="right-align">
                          <button class="waves-effect waves-light btn" type="submit">Enviar</button>
                      </div>
                  </div>
                </form>

            </div>
        </div>
    </div>
</div>

</div>

{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function(){
      $('select').formSelect();
    });
  </script>
{% endblock js %}